### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TonyStark** [tavyandy97/5paisa-js#1]
```data: { Message: 'Error while processing' }```
Trying to login but getting this error

**Comment by itdinesh** [comment]
> `data: { Message: 'Error while processing' }` Trying to login but getting this error

Hi @Tonystrack, this issue is resolved?

**Comment by TonyStark** [comment]
not using this anymore

**Comment by tavyandy97** [comment]
Hey @TonyStark , which package are you using now?

**Comment by TonyStark** [comment]
since my usage is limited im using 5paisa api using curl only
